/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-VersyPDF.h
 #	source generated by 4D Plugin Wizard
 #	Project : VersyPDF
 #	author : miyako
 #	2020/03/09
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_VERSYPDF_H
#define PLUGIN_VERSYPDF_H

#include "4DPluginAPI.h"

#include "C_TEXT.h"
#include "C_BLOB.h"
#include "C_LONGINT.h"

#include "4DPlugin-JSON.h"

#include "VersyPDF.h"

#include <vector>

#pragma mark -

void SIGN_PDF(PA_PluginParameters params);

#endif /* PLUGIN_VERSYPDF_H */
